### ISSUE TITLE
Readme issues

### ISSUE THREAD

**Issue by bazal4o** [stanislavtrifonov88/rentalcar#10]
* Convert the readme to real md formated file with headings and snippet styling 
   * Guidance - https://www.makeareadme.com/ 
   * Cheatsheet - https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet 

* errors in guidance 
    * Can't find api folder 

    * Docker command should either contain placeholders for user and pass, or explain you can change it later, because in the next step you talk about password the user has set, but he/she is not aware of it. 

    * Root level means the root folder where the readme lives, which will be the wrong place for .env and ormconfig

**Comment by stanislavtrifonov88** [comment]
fixed errors
formatted the doc
